/**
 * Curated Plant Lists
 *
 * When the USDA API doesn't return sufficient results (it has limited
 * search capabilities), we fall back to curated lists of well-known
 * species compiled from authoritative permaculture and horticultural
 * references:
 *
 * - USDA PLANTS Database (plants.usda.gov)
 * - Eric Toensmeier's "Perennial Vegetables" and "The Carbon Farming Solution"
 * - Dave Jacke & Eric Toensmeier's "Edible Forest Gardens" Vol 1 & 2
 * - Martin Crawford's "Creating a Forest Garden"
 * - Michael Dirr's "Manual of Woody Landscape Plants"
 * - Lady Bird Johnson Wildflower Center
 * - State extension service recommendations
 *
 * The AI enrichment step fills in permaculture-specific details.
 */

import type { ScrapedPlant, PlantCategory } from './types';

interface CuratedEntry {
  scientificName: string;
  commonName: string;
  family?: string;
  growthHabit: string;
  isNative: boolean;
  matureHeightFt?: number;
}

const CURATED_LISTS: Partial<Record<PlantCategory, CuratedEntry[]>> = {
  nitrogen_fixers: [
    { scientificName: 'Robinia pseudoacacia', commonName: 'Black Locust', growthHabit: 'Tree', isNative: true, matureHeightFt: 80 },
    { scientificName: 'Gleditsia triacanthos', commonName: 'Honey Locust', growthHabit: 'Tree', isNative: true, matureHeightFt: 70 },
    { scientificName: 'Gymnocladus dioicus', commonName: 'Kentucky Coffeetree', growthHabit: 'Tree', isNative: true, matureHeightFt: 60 },
    { scientificName: 'Alnus rubra', commonName: 'Red Alder', growthHabit: 'Tree', isNative: true, matureHeightFt: 50 },
    { scientificName: 'Alnus incana', commonName: 'Speckled Alder', growthHabit: 'Tree', isNative: true, matureHeightFt: 25 },
    { scientificName: 'Elaeagnus umbellata', commonName: 'Autumn Olive', growthHabit: 'Shrub', isNative: false, matureHeightFt: 18 },
    { scientificName: 'Elaeagnus angustifolia', commonName: 'Russian Olive', growthHabit: 'Tree', isNative: false, matureHeightFt: 25 },
    { scientificName: 'Shepherdia argentea', commonName: 'Silver Buffaloberry', growthHabit: 'Shrub', isNative: true, matureHeightFt: 15 },
    { scientificName: 'Shepherdia canadensis', commonName: 'Canada Buffaloberry', growthHabit: 'Shrub', isNative: true, matureHeightFt: 8 },
    { scientificName: 'Hippophae rhamnoides', commonName: 'Sea Buckthorn', growthHabit: 'Shrub', isNative: false, matureHeightFt: 20 },
    { scientificName: 'Ceanothus americanus', commonName: 'New Jersey Tea', growthHabit: 'Shrub', isNative: true, matureHeightFt: 4 },
    { scientificName: 'Myrica pensylvanica', commonName: 'Northern Bayberry', growthHabit: 'Shrub', isNative: true, matureHeightFt: 10 },
    { scientificName: 'Morella cerifera', commonName: 'Wax Myrtle', growthHabit: 'Shrub', isNative: true, matureHeightFt: 15 },
    { scientificName: 'Comptonia peregrina', commonName: 'Sweetfern', growthHabit: 'Shrub', isNative: true, matureHeightFt: 4 },
    { scientificName: 'Baptisia australis', commonName: 'Blue Wild Indigo', growthHabit: 'Forb/herb', isNative: true, matureHeightFt: 4 },
    { scientificName: 'Baptisia tinctoria', commonName: 'Yellow Wild Indigo', growthHabit: 'Forb/herb', isNative: true, matureHeightFt: 3 },
    { scientificName: 'Lupinus perennis', commonName: 'Wild Lupine', growthHabit: 'Forb/herb', isNative: true, matureHeightFt: 2 },
    { scientificName: 'Amorpha fruticosa', commonName: 'False Indigo Bush', growthHabit: 'Shrub', isNative: true, matureHeightFt: 12 },
    { scientificName: 'Amorpha canescens', commonName: 'Lead Plant', growthHabit: 'Shrub', isNative: true, matureHeightFt: 3 },
    { scientificName: 'Cercis canadensis', commonName: 'Eastern Redbud', growthHabit: 'Tree', isNative: true, matureHeightFt: 30 },
    { scientificName: 'Trifolium repens', commonName: 'White Clover', growthHabit: 'Forb/herb', isNative: false, matureHeightFt: 1 },
    { scientificName: 'Trifolium pratense', commonName: 'Red Clover', growthHabit: 'Forb/herb', isNative: false, matureHeightFt: 2 },
    { scientificName: 'Medicago sativa', commonName: 'Alfalfa', growthHabit: 'Forb/herb', isNative: false, matureHeightFt: 3 },
    { scientificName: 'Desmodium canadense', commonName: 'Showy Tick Trefoil', growthHabit: 'Forb/herb', isNative: true, matureHeightFt: 5 },
    { scientificName: 'Apios americana', commonName: 'Groundnut', growthHabit: 'Vine', isNative: true, matureHeightFt: 10 },
    { scientificName: 'Lespedeza capitata', commonName: 'Roundhead Bushclover', growthHabit: 'Forb/herb', isNative: true, matureHeightFt: 4 },
    { scientificName: 'Thermopsis villosa', commonName: 'Carolina Bushpea', growthHabit: 'Forb/herb', isNative: true, matureHeightFt: 4 },
    { scientificName: 'Wisteria frutescens', commonName: 'American Wisteria', growthHabit: 'Vine', isNative: true, matureHeightFt: 30 },
    { scientificName: 'Styphnolobium japonicum', commonName: 'Japanese Pagoda Tree', growthHabit: 'Tree', isNative: false, matureHeightFt: 60 },
    { scientificName: 'Cladrastis kentukea', commonName: 'Yellowwood', growthHabit: 'Tree', isNative: true, matureHeightFt: 50 },
  ],
  fruit_nut_trees: [
    { scientificName: 'Malus domestica', commonName: 'Apple', growthHabit: 'Tree', isNative: false, matureHeightFt: 25 },
    { scientificName: 'Malus coronaria', commonName: 'Sweet Crabapple', growthHabit: 'Tree', isNative: true, matureHeightFt: 25 },
    { scientificName: 'Pyrus communis', commonName: 'European Pear', growthHabit: 'Tree', isNative: false, matureHeightFt: 30 },
    { scientificName: 'Prunus persica', commonName: 'Peach', growthHabit: 'Tree', isNative: false, matureHeightFt: 20 },
    { scientificName: 'Prunus avium', commonName: 'Sweet Cherry', growthHabit: 'Tree', isNative: false, matureHeightFt: 35 },
    { scientificName: 'Prunus domestica', commonName: 'European Plum', growthHabit: 'Tree', isNative: false, matureHeightFt: 25 },
    { scientificName: 'Prunus americana', commonName: 'American Plum', growthHabit: 'Tree', isNative: true, matureHeightFt: 20 },
    { scientificName: 'Prunus serotina', commonName: 'Black Cherry', growthHabit: 'Tree', isNative: true, matureHeightFt: 70 },
    { scientificName: 'Prunus virginiana', commonName: 'Chokecherry', growthHabit: 'Tree', isNative: true, matureHeightFt: 25 },
    { scientificName: 'Juglans nigra', commonName: 'Black Walnut', growthHabit: 'Tree', isNative: true, matureHeightFt: 100 },
    { scientificName: 'Juglans cinerea', commonName: 'Butternut', growthHabit: 'Tree', isNative: true, matureHeightFt: 60 },
    { scientificName: 'Juglans regia', commonName: 'English Walnut', growthHabit: 'Tree', isNative: false, matureHeightFt: 60 },
    { scientificName: 'Carya illinoinensis', commonName: 'Pecan', growthHabit: 'Tree', isNative: true, matureHeightFt: 100 },
    { scientificName: 'Carya ovata', commonName: 'Shagbark Hickory', growthHabit: 'Tree', isNative: true, matureHeightFt: 80 },
    { scientificName: 'Carya laciniosa', commonName: 'Shellbark Hickory', growthHabit: 'Tree', isNative: true, matureHeightFt: 80 },
    { scientificName: 'Castanea dentata', commonName: 'American Chestnut', growthHabit: 'Tree', isNative: true, matureHeightFt: 80 },
    { scientificName: 'Castanea mollissima', commonName: 'Chinese Chestnut', growthHabit: 'Tree', isNative: false, matureHeightFt: 40 },
    { scientificName: 'Corylus americana', commonName: 'American Hazelnut', growthHabit: 'Shrub', isNative: true, matureHeightFt: 15 },
    { scientificName: 'Corylus avellana', commonName: 'European Hazelnut', growthHabit: 'Shrub', isNative: false, matureHeightFt: 15 },
    { scientificName: 'Asimina triloba', commonName: 'Pawpaw', growthHabit: 'Tree', isNative: true, matureHeightFt: 30 },
    { scientificName: 'Diospyros virginiana', commonName: 'American Persimmon', growthHabit: 'Tree', isNative: true, matureHeightFt: 60 },
    { scientificName: 'Morus rubra', commonName: 'Red Mulberry', growthHabit: 'Tree', isNative: true, matureHeightFt: 50 },
    { scientificName: 'Morus alba', commonName: 'White Mulberry', growthHabit: 'Tree', isNative: false, matureHeightFt: 40 },
    { scientificName: 'Amelanchier laevis', commonName: 'Allegheny Serviceberry', growthHabit: 'Tree', isNative: true, matureHeightFt: 25 },
    { scientificName: 'Amelanchier alnifolia', commonName: 'Saskatoon Serviceberry', growthHabit: 'Shrub', isNative: true, matureHeightFt: 15 },
    { scientificName: 'Celtis occidentalis', commonName: 'Common Hackberry', growthHabit: 'Tree', isNative: true, matureHeightFt: 60 },
    { scientificName: 'Crataegus mollis', commonName: 'Downy Hawthorn', growthHabit: 'Tree', isNative: true, matureHeightFt: 30 },
    { scientificName: 'Sambucus nigra', commonName: 'Elderberry', growthHabit: 'Shrub', isNative: false, matureHeightFt: 15 },
    { scientificName: 'Sambucus canadensis', commonName: 'American Elderberry', growthHabit: 'Shrub', isNative: true, matureHeightFt: 12 },
    { scientificName: 'Ficus carica', commonName: 'Common Fig', growthHabit: 'Tree', isNative: false, matureHeightFt: 20 },
    { scientificName: 'Pinus edulis', commonName: 'Pinyon Pine', growthHabit: 'Tree', isNative: true, matureHeightFt: 20 },
    { scientificName: 'Quercus macrocarpa', commonName: 'Bur Oak', growthHabit: 'Tree', isNative: true, matureHeightFt: 80 },
    { scientificName: 'Quercus alba', commonName: 'White Oak', growthHabit: 'Tree', isNative: true, matureHeightFt: 80 },
    { scientificName: 'Ginkgo biloba', commonName: 'Ginkgo', growthHabit: 'Tree', isNative: false, matureHeightFt: 80 },
    { scientificName: 'Ziziphus jujuba', commonName: 'Jujube', growthHabit: 'Tree', isNative: false, matureHeightFt: 25 },
  ],
  berry_bushes: [
    { scientificName: 'Vaccinium corymbosum', commonName: 'Highbush Blueberry', growthHabit: 'Shrub', isNative: true, matureHeightFt: 8 },
    { scientificName: 'Vaccinium angustifolium', commonName: 'Lowbush Blueberry', growthHabit: 'Shrub', isNative: true, matureHeightFt: 2 },
    { scientificName: 'Vaccinium macrocarpon', commonName: 'Cranberry', growthHabit: 'Shrub', isNative: true, matureHeightFt: 1 },
    { scientificName: 'Rubus idaeus', commonName: 'Red Raspberry', growthHabit: 'Shrub', isNative: false, matureHeightFt: 6 },
    { scientificName: 'Rubus occidentalis', commonName: 'Black Raspberry', growthHabit: 'Shrub', isNative: true, matureHeightFt: 6 },
    { scientificName: 'Rubus allegheniensis', commonName: 'Allegheny Blackberry', growthHabit: 'Shrub', isNative: true, matureHeightFt: 8 },
    { scientificName: 'Ribes nigrum', commonName: 'Black Currant', growthHabit: 'Shrub', isNative: false, matureHeightFt: 6 },
    { scientificName: 'Ribes rubrum', commonName: 'Red Currant', growthHabit: 'Shrub', isNative: false, matureHeightFt: 5 },
    { scientificName: 'Ribes uva-crispa', commonName: 'Gooseberry', growthHabit: 'Shrub', isNative: false, matureHeightFt: 4 },
    { scientificName: 'Ribes americanum', commonName: 'American Black Currant', growthHabit: 'Shrub', isNative: true, matureHeightFt: 5 },
    { scientificName: 'Aronia melanocarpa', commonName: 'Black Chokeberry', growthHabit: 'Shrub', isNative: true, matureHeightFt: 6 },
    { scientificName: 'Aronia arbutifolia', commonName: 'Red Chokeberry', growthHabit: 'Shrub', isNative: true, matureHeightFt: 10 },
    { scientificName: 'Viburnum trilobum', commonName: 'American Cranberrybush', growthHabit: 'Shrub', isNative: true, matureHeightFt: 12 },
    { scientificName: 'Viburnum prunifolium', commonName: 'Blackhaw', growthHabit: 'Shrub', isNative: true, matureHeightFt: 15 },
    { scientificName: 'Gaylussacia baccata', commonName: 'Black Huckleberry', growthHabit: 'Shrub', isNative: true, matureHeightFt: 3 },
    { scientificName: 'Rosa carolina', commonName: 'Carolina Rose', growthHabit: 'Shrub', isNative: true, matureHeightFt: 4 },
    { scientificName: 'Rosa rugosa', commonName: 'Rugosa Rose', growthHabit: 'Shrub', isNative: false, matureHeightFt: 6 },
    { scientificName: 'Lonicera caerulea', commonName: 'Honeyberry', growthHabit: 'Shrub', isNative: false, matureHeightFt: 6 },
    { scientificName: 'Elaeagnus multiflora', commonName: 'Goumi', growthHabit: 'Shrub', isNative: false, matureHeightFt: 8 },
    { scientificName: 'Lindera benzoin', commonName: 'Spicebush', growthHabit: 'Shrub', isNative: true, matureHeightFt: 12 },
    { scientificName: 'Callicarpa americana', commonName: 'American Beautyberry', growthHabit: 'Shrub', isNative: true, matureHeightFt: 6 },
    { scientificName: 'Ilex verticillata', commonName: 'Winterberry', growthHabit: 'Shrub', isNative: true, matureHeightFt: 12 },
    { scientificName: 'Mahonia aquifolium', commonName: 'Oregon Grape', growthHabit: 'Shrub', isNative: true, matureHeightFt: 6 },
    { scientificName: 'Fragaria virginiana', commonName: 'Wild Strawberry', growthHabit: 'Forb/herb', isNative: true, matureHeightFt: 1 },
  ],
  culinary_herbs: [
    { scientificName: 'Ocimum basilicum', commonName: 'Sweet Basil', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Mentha × piperita', commonName: 'Peppermint', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Mentha spicata', commonName: 'Spearmint', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Thymus vulgaris', commonName: 'Common Thyme', growthHabit: 'Subshrub', isNative: false },
    { scientificName: 'Salvia rosmarinus', commonName: 'Rosemary', growthHabit: 'Shrub', isNative: false },
    { scientificName: 'Salvia officinalis', commonName: 'Garden Sage', growthHabit: 'Subshrub', isNative: false },
    { scientificName: 'Origanum vulgare', commonName: 'Oregano', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Petroselinum crispum', commonName: 'Parsley', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Anethum graveolens', commonName: 'Dill', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Coriandrum sativum', commonName: 'Cilantro/Coriander', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Foeniculum vulgare', commonName: 'Fennel', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Allium schoenoprasum', commonName: 'Chives', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Allium tuberosum', commonName: 'Garlic Chives', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Artemisia dracunculus', commonName: 'Tarragon', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Lavandula angustifolia', commonName: 'English Lavender', growthHabit: 'Subshrub', isNative: false },
    { scientificName: 'Melissa officinalis', commonName: 'Lemon Balm', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Nepeta cataria', commonName: 'Catnip', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Chamaemelum nobile', commonName: 'Roman Chamomile', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Borago officinalis', commonName: 'Borage', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Monarda didyma', commonName: 'Bee Balm', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Monarda fistulosa', commonName: 'Wild Bergamot', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Agastache foeniculum', commonName: 'Anise Hyssop', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Levisticum officinale', commonName: 'Lovage', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Myrrhis odorata', commonName: 'Sweet Cicely', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Stevia rebaudiana', commonName: 'Stevia', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Cymbopogon citratus', commonName: 'Lemongrass', growthHabit: 'Graminoid', isNative: false },
  ],
  vegetables_annuals: [
    { scientificName: 'Solanum lycopersicum', commonName: 'Tomato', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Capsicum annuum', commonName: 'Bell Pepper', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Cucurbita pepo', commonName: 'Summer Squash/Zucchini', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Cucurbita maxima', commonName: 'Winter Squash', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Cucurbita moschata', commonName: 'Butternut Squash', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Phaseolus vulgaris', commonName: 'Common Bean', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Phaseolus lunatus', commonName: 'Lima Bean', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Zea mays', commonName: 'Corn/Maize', growthHabit: 'Graminoid', isNative: true },
    { scientificName: 'Brassica oleracea var. capitata', commonName: 'Cabbage', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Brassica oleracea var. italica', commonName: 'Broccoli', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Brassica oleracea var. botrytis', commonName: 'Cauliflower', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Brassica rapa', commonName: 'Turnip', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Brassica oleracea var. gemmifera', commonName: 'Brussels Sprouts', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Brassica oleracea var. sabellica', commonName: 'Kale', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Lactuca sativa', commonName: 'Lettuce', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Daucus carota subsp. sativus', commonName: 'Carrot', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Beta vulgaris', commonName: 'Beet/Chard', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Allium cepa', commonName: 'Onion', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Allium sativum', commonName: 'Garlic', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Pisum sativum', commonName: 'Garden Pea', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Spinacia oleracea', commonName: 'Spinach', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Cucumis sativus', commonName: 'Cucumber', growthHabit: 'Vine', isNative: false },
    { scientificName: 'Cucumis melo', commonName: 'Cantaloupe/Melon', growthHabit: 'Vine', isNative: false },
    { scientificName: 'Citrullus lanatus', commonName: 'Watermelon', growthHabit: 'Vine', isNative: false },
    { scientificName: 'Ipomoea batatas', commonName: 'Sweet Potato', growthHabit: 'Vine', isNative: false },
    { scientificName: 'Solanum tuberosum', commonName: 'Potato', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Solanum melongena', commonName: 'Eggplant', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Raphanus sativus', commonName: 'Radish', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Abelmoschus esculentus', commonName: 'Okra', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Asparagus officinalis', commonName: 'Asparagus', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Cynara cardunculus', commonName: 'Artichoke/Cardoon', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Helianthus tuberosus', commonName: 'Jerusalem Artichoke', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Chenopodium quinoa', commonName: 'Quinoa', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Amaranthus cruentus', commonName: 'Amaranth', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Helianthus annuus', commonName: 'Sunflower', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Apium graveolens', commonName: 'Celery', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Pastinaca sativa', commonName: 'Parsnip', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Brassica napus', commonName: 'Rutabaga', growthHabit: 'Forb/herb', isNative: false },
  ],
  cover_crops: [
    { scientificName: 'Trifolium incarnatum', commonName: 'Crimson Clover', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Vicia villosa', commonName: 'Hairy Vetch', growthHabit: 'Vine', isNative: false },
    { scientificName: 'Vicia faba', commonName: 'Fava Bean', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Secale cereale', commonName: 'Winter Rye', growthHabit: 'Graminoid', isNative: false },
    { scientificName: 'Fagopyrum esculentum', commonName: 'Buckwheat', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Brassica juncea', commonName: 'Mustard', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Phacelia tanacetifolia', commonName: 'Lacy Phacelia', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Lupinus albus', commonName: 'White Lupine', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Avena sativa', commonName: 'Oats', growthHabit: 'Graminoid', isNative: false },
    { scientificName: 'Lolium multiflorum', commonName: 'Annual Ryegrass', growthHabit: 'Graminoid', isNative: false },
    { scientificName: 'Raphanus sativus var. longipinnatus', commonName: 'Tillage Radish/Daikon', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Sinapis alba', commonName: 'White Mustard', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Pisum sativum subsp. arvense', commonName: 'Field Pea', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Sorghum bicolor', commonName: 'Sorghum-Sudan', growthHabit: 'Graminoid', isNative: false },
    { scientificName: 'Vigna unguiculata', commonName: 'Cowpea/Southern Pea', growthHabit: 'Forb/herb', isNative: false },
  ],
  groundcovers: [
    { scientificName: 'Fragaria vesca', commonName: 'Woodland Strawberry', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Trifolium repens', commonName: 'White Dutch Clover', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Thymus serpyllum', commonName: 'Creeping Thyme', growthHabit: 'Subshrub', isNative: false },
    { scientificName: 'Asarum canadense', commonName: 'Wild Ginger', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Tiarella cordifolia', commonName: 'Foamflower', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Waldsteinia fragarioides', commonName: 'Barren Strawberry', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Phlox subulata', commonName: 'Creeping Phlox', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Gaultheria procumbens', commonName: 'Wintergreen', growthHabit: 'Subshrub', isNative: true },
    { scientificName: 'Mitchella repens', commonName: 'Partridgeberry', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Pachysandra procumbens', commonName: 'Allegheny Spurge', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Sedum ternatum', commonName: 'Woodland Stonecrop', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Chrysogonum virginianum', commonName: 'Green and Gold', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Prunella vulgaris', commonName: 'Self-Heal', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Ajuga reptans', commonName: 'Bugleweed', growthHabit: 'Forb/herb', isNative: false },
    { scientificName: 'Vinca minor', commonName: 'Periwinkle', growthHabit: 'Subshrub', isNative: false },
  ],
  vines: [
    { scientificName: 'Vitis labrusca', commonName: 'Fox Grape', growthHabit: 'Vine', isNative: true },
    { scientificName: 'Vitis riparia', commonName: 'Riverbank Grape', growthHabit: 'Vine', isNative: true },
    { scientificName: 'Vitis vinifera', commonName: 'European Wine Grape', growthHabit: 'Vine', isNative: false },
    { scientificName: 'Actinidia arguta', commonName: 'Hardy Kiwi', growthHabit: 'Vine', isNative: false },
    { scientificName: 'Actinidia kolomikta', commonName: 'Arctic Kiwi', growthHabit: 'Vine', isNative: false },
    { scientificName: 'Passiflora incarnata', commonName: 'Maypop', growthHabit: 'Vine', isNative: true },
    { scientificName: 'Humulus lupulus', commonName: 'Hops', growthHabit: 'Vine', isNative: true },
    { scientificName: 'Schisandra chinensis', commonName: 'Five Flavor Berry', growthHabit: 'Vine', isNative: false },
    { scientificName: 'Akebia quinata', commonName: 'Chocolate Vine', growthHabit: 'Vine', isNative: false },
    { scientificName: 'Apios americana', commonName: 'Groundnut', growthHabit: 'Vine', isNative: true },
    { scientificName: 'Clematis virginiana', commonName: 'Virgin\'s Bower', growthHabit: 'Vine', isNative: true },
    { scientificName: 'Lonicera sempervirens', commonName: 'Coral Honeysuckle', growthHabit: 'Vine', isNative: true },
    { scientificName: 'Campsis radicans', commonName: 'Trumpet Vine', growthHabit: 'Vine', isNative: true },
    { scientificName: 'Parthenocissus quinquefolia', commonName: 'Virginia Creeper', growthHabit: 'Vine', isNative: true },
    { scientificName: 'Celastrus scandens', commonName: 'American Bittersweet', growthHabit: 'Vine', isNative: true },
    { scientificName: 'Aristolochia macrophylla', commonName: 'Dutchman\'s Pipe', growthHabit: 'Vine', isNative: true },
    { scientificName: 'Wisteria frutescens', commonName: 'American Wisteria', growthHabit: 'Vine', isNative: true },
  ],
  aquatic_plants: [
    { scientificName: 'Typha latifolia', commonName: 'Common Cattail', growthHabit: 'Forb/herb', isNative: true, matureHeightFt: 8 },
    { scientificName: 'Sagittaria latifolia', commonName: 'Broadleaf Arrowhead', growthHabit: 'Forb/herb', isNative: true, matureHeightFt: 4 },
    { scientificName: 'Pontederia cordata', commonName: 'Pickerelweed', growthHabit: 'Forb/herb', isNative: true, matureHeightFt: 3 },
    { scientificName: 'Nymphaea odorata', commonName: 'American White Waterlily', growthHabit: 'Forb/herb', isNative: true, matureHeightFt: 1 },
    { scientificName: 'Nelumbo lutea', commonName: 'American Lotus', growthHabit: 'Forb/herb', isNative: true, matureHeightFt: 3 },
    { scientificName: 'Iris versicolor', commonName: 'Blue Flag Iris', growthHabit: 'Forb/herb', isNative: true, matureHeightFt: 3 },
    { scientificName: 'Caltha palustris', commonName: 'Marsh Marigold', growthHabit: 'Forb/herb', isNative: true, matureHeightFt: 2 },
    { scientificName: 'Acorus calamus', commonName: 'Sweet Flag', growthHabit: 'Forb/herb', isNative: true, matureHeightFt: 4 },
    { scientificName: 'Juncus effusus', commonName: 'Soft Rush', growthHabit: 'Graminoid', isNative: true, matureHeightFt: 4 },
    { scientificName: 'Schoenoplectus tabernaemontani', commonName: 'Softstem Bulrush', growthHabit: 'Graminoid', isNative: true, matureHeightFt: 8 },
    { scientificName: 'Cephalanthus occidentalis', commonName: 'Buttonbush', growthHabit: 'Shrub', isNative: true, matureHeightFt: 12 },
    { scientificName: 'Myriophyllum aquaticum', commonName: 'Parrot Feather', growthHabit: 'Forb/herb', isNative: false, matureHeightFt: 1 },
    { scientificName: 'Orontium aquaticum', commonName: 'Golden Club', growthHabit: 'Forb/herb', isNative: true, matureHeightFt: 2 },
    { scientificName: 'Peltandra virginica', commonName: 'Arrow Arum', growthHabit: 'Forb/herb', isNative: true, matureHeightFt: 3 },
    { scientificName: 'Saururus cernuus', commonName: 'Lizard\'s Tail', growthHabit: 'Forb/herb', isNative: true, matureHeightFt: 3 },
    { scientificName: 'Zizania palustris', commonName: 'Wild Rice', growthHabit: 'Graminoid', isNative: true, matureHeightFt: 8 },
    { scientificName: 'Decodon verticillatus', commonName: 'Water Willow', growthHabit: 'Shrub', isNative: true, matureHeightFt: 8 },
    { scientificName: 'Lobelia cardinalis', commonName: 'Cardinal Flower', growthHabit: 'Forb/herb', isNative: true, matureHeightFt: 4 },
    { scientificName: 'Chelone glabra', commonName: 'White Turtlehead', growthHabit: 'Forb/herb', isNative: true, matureHeightFt: 3 },
    { scientificName: 'Eupatorium perfoliatum', commonName: 'Common Boneset', growthHabit: 'Forb/herb', isNative: true, matureHeightFt: 4 },
  ],
  pollinator_plants: [
    { scientificName: 'Asclepias tuberosa', commonName: 'Butterfly Milkweed', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Asclepias syriaca', commonName: 'Common Milkweed', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Asclepias incarnata', commonName: 'Swamp Milkweed', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Monarda fistulosa', commonName: 'Wild Bergamot', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Solidago canadensis', commonName: 'Canada Goldenrod', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Symphyotrichum novae-angliae', commonName: 'New England Aster', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Echinacea purpurea', commonName: 'Purple Coneflower', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Echinacea pallida', commonName: 'Pale Purple Coneflower', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Rudbeckia hirta', commonName: 'Black-Eyed Susan', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Rudbeckia laciniata', commonName: 'Cutleaf Coneflower', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Coreopsis lanceolata', commonName: 'Lanceleaf Coreopsis', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Helianthus maximiliani', commonName: 'Maximilian Sunflower', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Ratibida pinnata', commonName: 'Gray-Headed Coneflower', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Vernonia noveboracensis', commonName: 'New York Ironweed', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Pycnanthemum virginianum', commonName: 'Virginia Mountain Mint', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Zizia aurea', commonName: 'Golden Alexander', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Liatris spicata', commonName: 'Dense Blazing Star', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Penstemon digitalis', commonName: 'Foxglove Beardtongue', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Baptisia australis', commonName: 'Blue Wild Indigo', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Chelone lyonii', commonName: 'Pink Turtlehead', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Eutrochium purpureum', commonName: 'Joe Pye Weed', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Eupatorium perfoliatum', commonName: 'Boneset', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Achillea millefolium', commonName: 'Yarrow', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Eryngium yuccifolium', commonName: 'Rattlesnake Master', growthHabit: 'Forb/herb', isNative: true },
    { scientificName: 'Silphium perfoliatum', commonName: 'Cup Plant', growthHabit: 'Forb/herb', isNative: true },
  ],
};

/**
 * Get curated plant list for a category.
 * Returns ScrapedPlant objects ready for AI enrichment.
 */
export function getCuratedPlants(category: PlantCategory): ScrapedPlant[] {
  const entries = CURATED_LISTS[category];
  if (!entries) return [];

  return entries.map(entry => ({
    symbol: entry.scientificName.replace(/\s+/g, '').substring(0, 6).toUpperCase(),
    commonName: entry.commonName,
    scientificName: entry.scientificName,
    family: entry.family || '',
    growthHabit: entry.growthHabit,
    duration: 'Perennial',
    isNative: entry.isNative,
    nativeStatus: entry.isNative ? 'L48(N)' : 'L48(I)',
    matureHeightFt: entry.matureHeightFt || null,
    matureWidthFt: entry.matureHeightFt ? Math.round(entry.matureHeightFt * 0.6) : null,
    sunRequirements: null,
    waterRequirements: null,
    minHardinessZone: null,
    maxHardinessZone: null,
    minRainfallInches: null,
    maxRainfallInches: null,
    bloomPeriod: null,
    droughtTolerance: null,
    nitrogenFixation: null,
    shadeTolerance: null,
    palatableHuman: null,
    fruitSeedPeriod: null,
  }));
}
